
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body>
      <header style={{backgroundColor:"red"}}>
        <p>
           I  am header
        </p>
      </header>
     
        {children}
      
      <footer>
        <p>I am footer</p>
      </footer>
      </body>
    </html>
  );
}
